





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace DNG.Foundation.ORM
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; set; }

		[SitecoreInfo(SitecoreInfoType.Language)]
    Sitecore.Globalization.Language Language{ get; set; }

    [SitecoreInfo(SitecoreInfoType.Version)]
    int Version { get; set; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
    public virtual Sitecore.Globalization.Language Language{ get; set; }

    [SitecoreInfo(SitecoreInfoType.Version)]
    public virtual int Version { get; set; }

	}
}
namespace DNG.Foundation.ORM
{


 	/// <summary>
	/// I_Page_Base Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/DNG/_Page Base</para>	
	/// <para>ID: 217e5fce-c6d7-44a5-b774-90b9a7cd7ccd</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Page_BaseConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Page_Base : IGlassBase 
	{
								/// <summary>
					/// The DemoForARM field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ab365e08-9498-47ef-adda-043b08398762</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Page_BaseConstants.DemoForARMFieldName )]
					string DemoForARM  {get; set;}
			
								/// <summary>
					/// The Page Content field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 3b84f0f9-4ba7-4bac-976f-5570736c06da</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Page_BaseConstants.Page_ContentFieldName , Setting = SitecoreFieldSettings.RichTextRaw)]
					string Page_Content  {get; set;}
			
								/// <summary>
					/// The Page SubDescription field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: cfda20be-97a5-43ad-a225-f9d077ad4e32</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Page_BaseConstants.Page_SubDescriptionFieldName )]
					string Page_SubDescription  {get; set;}
			
								/// <summary>
					/// The Page Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 49095396-5900-4fca-bea9-e304285ea1e4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Page_BaseConstants.Page_TitleFieldName )]
					string Page_Title  {get; set;}
			
								/// <summary>
					/// The ReleaseNumber field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: dbbbfb23-fee7-4d81-881f-7a8717adcd7c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Page_BaseConstants.ReleaseNumberFieldName )]
					string ReleaseNumber  {get; set;}
			
								/// <summary>
					/// The DeploymentNumber field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 4f8478c3-cd6d-4a63-8577-243470ad5a6d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Page_BaseConstants.DeploymentNumberFieldName )]
					string DeploymentNumber  {get; set;}
			
				}


	public static partial class I_Page_BaseConstants{

			public const string TemplateIdString = "217e5fce-c6d7-44a5-b774-90b9a7cd7ccd";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Page Base";

					
			public static readonly ID DemoForARMFieldId = new ID("ab365e08-9498-47ef-adda-043b08398762");
			public const string DemoForARMFieldName = "DemoForARM";
			
					
			public static readonly ID Page_ContentFieldId = new ID("3b84f0f9-4ba7-4bac-976f-5570736c06da");
			public const string Page_ContentFieldName = "Page Content";
			
					
			public static readonly ID Page_SubDescriptionFieldId = new ID("cfda20be-97a5-43ad-a225-f9d077ad4e32");
			public const string Page_SubDescriptionFieldName = "Page SubDescription";
			
					
			public static readonly ID Page_TitleFieldId = new ID("49095396-5900-4fca-bea9-e304285ea1e4");
			public const string Page_TitleFieldName = "Page Title";
			
					
			public static readonly ID ReleaseNumberFieldId = new ID("dbbbfb23-fee7-4d81-881f-7a8717adcd7c");
			public const string ReleaseNumberFieldName = "ReleaseNumber";
			
					
			public static readonly ID DeploymentNumberFieldId = new ID("4f8478c3-cd6d-4a63-8577-243470ad5a6d");
			public const string DeploymentNumberFieldName = "DeploymentNumber";
			
			

	}

	
	/// <summary>
	/// _Page_Base
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/DNG/_Page Base</para>	
	/// <para>ID: 217e5fce-c6d7-44a5-b774-90b9a7cd7ccd</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Page_BaseConstants.TemplateIdString )] //, Cachable = true
	public partial class _Page_Base  : GlassBase, I_Page_Base 
	{
	   
						/// <summary>
				/// The DemoForARM field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ab365e08-9498-47ef-adda-043b08398762</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Page_BaseConstants.DemoForARMFieldName )]
				public virtual string DemoForARM  {get; set;}
					
						/// <summary>
				/// The Page Content field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 3b84f0f9-4ba7-4bac-976f-5570736c06da</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Page_BaseConstants.Page_ContentFieldName , Setting = SitecoreFieldSettings.RichTextRaw)]
				public virtual string Page_Content  {get; set;}
					
						/// <summary>
				/// The Page SubDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: cfda20be-97a5-43ad-a225-f9d077ad4e32</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Page_BaseConstants.Page_SubDescriptionFieldName )]
				public virtual string Page_SubDescription  {get; set;}
					
						/// <summary>
				/// The Page Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 49095396-5900-4fca-bea9-e304285ea1e4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Page_BaseConstants.Page_TitleFieldName )]
				public virtual string Page_Title  {get; set;}
					
						/// <summary>
				/// The ReleaseNumber field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: dbbbfb23-fee7-4d81-881f-7a8717adcd7c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Page_BaseConstants.ReleaseNumberFieldName )]
				public virtual string ReleaseNumber  {get; set;}
					
						/// <summary>
				/// The DeploymentNumber field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 4f8478c3-cd6d-4a63-8577-243470ad5a6d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Page_BaseConstants.DeploymentNumberFieldName )]
				public virtual string DeploymentNumber  {get; set;}
					
			
	}
}
namespace DNG.Foundation.ORM
{


 	/// <summary>
	/// IHome Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/DNG/Home</para>	
	/// <para>ID: 6f36b575-538b-4c24-a95a-bf6b72f3420f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHome : IGlassBase , global::DNG.Foundation.ORM.I_Page_Base
	{
				}


	public static partial class IHomeConstants{

			public const string TemplateIdString = "6f36b575-538b-4c24-a95a-bf6b72f3420f";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home";

					
			public static readonly ID DemoForARMFieldId = new ID("ab365e08-9498-47ef-adda-043b08398762");
			public const string DemoForARMFieldName = "DemoForARM";
			
					
			public static readonly ID Page_ContentFieldId = new ID("3b84f0f9-4ba7-4bac-976f-5570736c06da");
			public const string Page_ContentFieldName = "Page Content";
			
					
			public static readonly ID Page_SubDescriptionFieldId = new ID("cfda20be-97a5-43ad-a225-f9d077ad4e32");
			public const string Page_SubDescriptionFieldName = "Page SubDescription";
			
					
			public static readonly ID Page_TitleFieldId = new ID("49095396-5900-4fca-bea9-e304285ea1e4");
			public const string Page_TitleFieldName = "Page Title";
			
					
			public static readonly ID ReleaseNumberFieldId = new ID("dbbbfb23-fee7-4d81-881f-7a8717adcd7c");
			public const string ReleaseNumberFieldName = "ReleaseNumber";
			
					
			public static readonly ID DeploymentNumberFieldId = new ID("4f8478c3-cd6d-4a63-8577-243470ad5a6d");
			public const string DeploymentNumberFieldName = "DeploymentNumber";
			
			

	}

	
	/// <summary>
	/// Home
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/DNG/Home</para>	
	/// <para>ID: 6f36b575-538b-4c24-a95a-bf6b72f3420f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString )] //, Cachable = true
	public partial class Home  : GlassBase, IHome 
	{
	   
						/// <summary>
				/// The DemoForARM field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ab365e08-9498-47ef-adda-043b08398762</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.DemoForARMFieldName )]
				public virtual string DemoForARM  {get; set;}
					
						/// <summary>
				/// The Page Content field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 3b84f0f9-4ba7-4bac-976f-5570736c06da</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Page_ContentFieldName , Setting = SitecoreFieldSettings.RichTextRaw)]
				public virtual string Page_Content  {get; set;}
					
						/// <summary>
				/// The Page SubDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: cfda20be-97a5-43ad-a225-f9d077ad4e32</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Page_SubDescriptionFieldName )]
				public virtual string Page_SubDescription  {get; set;}
					
						/// <summary>
				/// The Page Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 49095396-5900-4fca-bea9-e304285ea1e4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Page_TitleFieldName )]
				public virtual string Page_Title  {get; set;}
					
						/// <summary>
				/// The ReleaseNumber field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: dbbbfb23-fee7-4d81-881f-7a8717adcd7c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.ReleaseNumberFieldName )]
				public virtual string ReleaseNumber  {get; set;}
					
						/// <summary>
				/// The DeploymentNumber field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 4f8478c3-cd6d-4a63-8577-243470ad5a6d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.DeploymentNumberFieldName )]
				public virtual string DeploymentNumber  {get; set;}
					
			
	}
}
namespace DNG.Foundation.ORM
{


 	/// <summary>
	/// ITenant Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Foundation/Multisite/Tenant</para>	
	/// <para>ID: 93ebcd14-7566-4111-a262-1f91f6b62f86</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITenantConstants.TemplateIdString )] //, Cachable = true
	public partial interface ITenant : IGlassBase 
	{
				}


	public static partial class ITenantConstants{

			public const string TemplateIdString = "93ebcd14-7566-4111-a262-1f91f6b62f86";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Tenant";

			

	}

	
	/// <summary>
	/// Tenant
	/// <para></para>
	/// <para>Path: /sitecore/templates/Foundation/Multisite/Tenant</para>	
	/// <para>ID: 93ebcd14-7566-4111-a262-1f91f6b62f86</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITenantConstants.TemplateIdString )] //, Cachable = true
	public partial class Tenant  : GlassBase, ITenant 
	{
	   
			
	}
}
namespace DNG.Foundation.ORM
{


 	/// <summary>
	/// IContent_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/DNG/Content Page</para>	
	/// <para>ID: dc4f2946-4307-4f48-ba78-e5daa509f11b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IContent_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IContent_Page : IGlassBase , global::DNG.Foundation.ORM.I_Page_Base
	{
				}


	public static partial class IContent_PageConstants{

			public const string TemplateIdString = "dc4f2946-4307-4f48-ba78-e5daa509f11b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Content Page";

					
			public static readonly ID DemoForARMFieldId = new ID("ab365e08-9498-47ef-adda-043b08398762");
			public const string DemoForARMFieldName = "DemoForARM";
			
					
			public static readonly ID Page_ContentFieldId = new ID("3b84f0f9-4ba7-4bac-976f-5570736c06da");
			public const string Page_ContentFieldName = "Page Content";
			
					
			public static readonly ID Page_SubDescriptionFieldId = new ID("cfda20be-97a5-43ad-a225-f9d077ad4e32");
			public const string Page_SubDescriptionFieldName = "Page SubDescription";
			
					
			public static readonly ID Page_TitleFieldId = new ID("49095396-5900-4fca-bea9-e304285ea1e4");
			public const string Page_TitleFieldName = "Page Title";
			
					
			public static readonly ID ReleaseNumberFieldId = new ID("dbbbfb23-fee7-4d81-881f-7a8717adcd7c");
			public const string ReleaseNumberFieldName = "ReleaseNumber";
			
					
			public static readonly ID DeploymentNumberFieldId = new ID("4f8478c3-cd6d-4a63-8577-243470ad5a6d");
			public const string DeploymentNumberFieldName = "DeploymentNumber";
			
			

	}

	
	/// <summary>
	/// Content_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/DNG/Content Page</para>	
	/// <para>ID: dc4f2946-4307-4f48-ba78-e5daa509f11b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IContent_PageConstants.TemplateIdString )] //, Cachable = true
	public partial class Content_Page  : GlassBase, IContent_Page 
	{
	   
						/// <summary>
				/// The DemoForARM field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ab365e08-9498-47ef-adda-043b08398762</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.DemoForARMFieldName )]
				public virtual string DemoForARM  {get; set;}
					
						/// <summary>
				/// The Page Content field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 3b84f0f9-4ba7-4bac-976f-5570736c06da</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.Page_ContentFieldName , Setting = SitecoreFieldSettings.RichTextRaw)]
				public virtual string Page_Content  {get; set;}
					
						/// <summary>
				/// The Page SubDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: cfda20be-97a5-43ad-a225-f9d077ad4e32</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.Page_SubDescriptionFieldName )]
				public virtual string Page_SubDescription  {get; set;}
					
						/// <summary>
				/// The Page Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 49095396-5900-4fca-bea9-e304285ea1e4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.Page_TitleFieldName )]
				public virtual string Page_Title  {get; set;}
					
						/// <summary>
				/// The ReleaseNumber field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: dbbbfb23-fee7-4d81-881f-7a8717adcd7c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.ReleaseNumberFieldName )]
				public virtual string ReleaseNumber  {get; set;}
					
						/// <summary>
				/// The DeploymentNumber field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 4f8478c3-cd6d-4a63-8577-243470ad5a6d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.DeploymentNumberFieldName )]
				public virtual string DeploymentNumber  {get; set;}
					
			
	}
}
namespace DNG.Foundation.ORM
{


 	/// <summary>
	/// ISite Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Foundation/Multisite/Site</para>	
	/// <para>ID: f646954a-7932-479f-b00e-3b3fe324915c</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISite : IGlassBase 
	{
				}


	public static partial class ISiteConstants{

			public const string TemplateIdString = "f646954a-7932-479f-b00e-3b3fe324915c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site";

			

	}

	
	/// <summary>
	/// Site
	/// <para></para>
	/// <para>Path: /sitecore/templates/Foundation/Multisite/Site</para>	
	/// <para>ID: f646954a-7932-479f-b00e-3b3fe324915c</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString )] //, Cachable = true
	public partial class Site  : GlassBase, ISite 
	{
	   
			
	}
}
